### ISSUE TITLE
NameError: Unknown variable: 'sqrt'

### ISSUE THREAD

**Issue by gituliar** [gituliar/fuchsia#12]
Let us improve I/O functions, so that Fuchsia deals correctly with matrices which contain `sqrt(?)` and `Sqrt[?]` objects.

**Comment by magv** [comment]
You can add something like [1] to the main branch.

[1] https://github.com/gituliar/fuchsia/commit/58388a97d98021ba5e7c5ddcff7d63a90bbc399c

**Comment by ChristophDlapa** [comment]
Is this implemented in the newest version? Unfortunately I cannot get past this error:

NameError: Unknown variable: 'RootOf'

**Comment by vsht** [comment]
I'm not a fuchsia dev, but from my experience the appearance of square roots might signal that your matrix requires a nonlinear variable transformation before it can be turned into a canonical form. The CPP version of Fuchsia ([github.com/magv/fuchsia.cpp](url)) has an option `suggest-changevar` that will analyze the matrix and suggest the appropriate transformation, if required. Perhaps you could try that first.

**Comment by magv** [comment]
The original issue here was fixed in a6db3aa544f6dde2f98d00bd18ffd4c42458171f.

What you're seeing is probably due to using `--use-maple` and a having a polynomial in the denominator that Maple can not solve with just roots -- it returns `RootOf(poly, x)` in these cases. Probably a spurious pole with a mixture of `x` and `eps`, right? Such poles usually happen either because your IBP routine gave you more masters than it should (i.e. there are linear relations between the masters), or because of an unfortunate master selection (i.e. you can choose different masters, and this spurious pole will go away).

Unfortunately the underlying CAS we're using -- Sagemath&Maxima do not have an equivalent of Maple's RootOf (AFAIK), so just importing that function will be of little benefit overall, as the reduction will choke a few steps later.

There is a somewhat better strategy of dealing with such spurious poles: they can be transformed away separately without the need for solving the polynomials. Think of it this way: if choosing different masters can remove this pole, then we know that a rational transformation exists that does it for us. At the moment we don't have it implemented though, and rotating the master selection is what we do in practice.

In any case, these poles is a problem many people have run into (Vladyslav have been asking about it in #16 for example), so I'm bound to fix it at some point. I've opened issue #17 for this, and I'll close this issue since the original problem is fixed.
