### ISSUE TITLE
Different output when using Maple and Maxima

### ISSUE THREAD

**Issue by vsht** [gituliar/fuchsia#15]
I was playing with the following simple example

```
cat ex1_ode_y.m
```

```
{{0,0},{-(eps-1)/(m2*y),eps/(y+1)+eps/(y-1)-1/y}}
```
from Oleksandr's lecture at the CAPP 2017 school at DESY. I'm a bit puzzled that running Fuchsia with or without the `--use-maple` option seems to produce different results. C.f.

```
$sage -python fuchsia.py reduce -x y -m ex1_ode_y_eps1.m -t ex1_ode_y_eps_t1.m ex1_ode_y.m
$sage -python fuchsia.py reduce --use-maple -x y -m ex1_ode_y_eps2.m -t ex1_ode_y_eps_t2.m ex1_ode_y.m 
```

```
$diff ex1_ode_y_eps1.m  ex1_ode_y_eps2.m

1c1
< {{0,0},{2/3*eps/(m2*(y+1))-2/3*eps/(m2*(y-1)),eps/(y+1)+eps/(y-1)}}
\ No newline at end of file
---
> {{0,0},{eps/(m2*(y+1))-eps/(m2*(y-1)),eps/(y+1)+eps/(y-1)}}
\ No newline at end of file
```

```
$diff ex1_ode_y_eps_t1.m  ex1_ode_y_eps_t2.m

1c1
< {{4/3*(2*eps-1)/(eps-1),0},{4/3/m2,-2/y}}
\ No newline at end of file
---
> {{-(2*eps-1)/(eps-1),0},{-1/m2,1/y}}
\ No newline at end of file
```

Is this expected?

I'm running Fedora 26 and have Maple 2015.2 installed.

**Comment by gituliar** [comment]
Hello @vsht, and thanks for the message.

Yes, such a result is expected unless produced transformations lead to the epsilon form. The reason is that an epsilon form for a given matrix is not unique and Fuchsia finds only one of them (it is exactly what we need in practice to further solve differential equations). The results could vary even if you stick to Maxima or Maple, but change some random seed parameters inside Fuchsia.

**Comment by vsht** [comment]
I see, many thanks for the explanation.
