### ISSUE TITLE
[Algirithm 2] Avoid tremendous polynoms in eps

### ISSUE THREAD

**Issue by gituliar** [gituliar/fuchsia#3]
When fuchsifying `git_410.mtx` I get ratios of huge polynoms in eps, i.e., O(10) and 11 digit coefficients. In comparison, R.Lee sent me a tranformation for this system in a very simple form. Can we optimize our algorithm to avoid such a mess?

**Comment by magv** [comment]
We're still missing algorithm 3. Until it is implemented, it makes little sense to look at the resulting matrix, since it is intermediary.

**Comment by gituliar** [comment]
I am almost done with Algorithm 3. It can deal with `git_409.mtx`, but `git_410.mtx` looks too complicated. I need more time to polish the code before commiting, but the core is already ready.

In any case, dealing with such huge expressions at the intermediate step for such a relatively simple matrix is dangerous, execution may hang at some point. Try to think if it possible to optimize that somehow.

**Comment by magv** [comment]
`git_410_x-1_x_x+1.mtx` is infinite at `x->oo`; we'd have simpler expressions too if we'd allow that to happen.

It is possible to apply transformations to the matrix to try to reduce it's size, and that is an interesting question, but that won't likely to be a one-line change -- that will be a new separate algorithm. I mean, I'll look into it, sure, but don't expect a quick solution here.

**Comment by magv** [comment]
OK, so this issue is "fixed" for the moment. The fixes are:

1. Slightly improved `fuchsify` from 674322d7883b660b5cf889d10fbb6a9169ca0c72. This eliminates many pathological cases, and makes the resulting matrices with most seeds passable.

2. Simplification functions from ba2082e7f1eb5f7722d8d9b79544527fe1338482. You should apply `simplify_by_factorization` to any matrix before passing it into `fuchsify`, and then apply `simplify_by_jordanification` right after factorizing epsilon (or maybe even after normalization).

The overall effect of these changes is that git410 example passed through `simplify_by_factorization`, `fuchsify`, `normalize`, `factor_epsilon` and `simplify_by_jordanification` is not significantly worse than the one you got from R. Lee.

(The combined transformation matrix on the other hand is pretty bad).
